/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: denis_cliofas (https://sketchfab.com/denis_cliofas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/comic-drone-f2489a3e66ee4aeb86b8d02568ffe750
Title: Comic Drone
*/

import React, { useEffect, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useMediaQuery } from 'react-responsive'

export function Drone(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/comic_drone.glb')
  const { actions } = useAnimations(animations, group)
  const isMobile = useMediaQuery({ maxWidth: 853 });
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play()
    }
  }, [actions, animations]);

  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.003
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
  <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={isMobile ? 0.18 : 0.09}>
          <group name="f337b629572e4d64ad830bb62fa78296fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Drone" />
                <group
                  name="Armature"
                  position={[-6.283, 0.022, 6.252]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    {Object.entries(nodes).map(([name, node]) =>
                      node.geometry ? (
                        <skinnedMesh
                          key={name}
                          geometry={node.geometry}
                          material={node.material || Object.values(materials)[0]}
                          skeleton={node.skeleton}
                        />
                      ) : null
                    )}
                    <group name="Object_8" />
                    <group name="Object_24" />
                    <group name="Object_28" position={[-6.283, 3, 6.252]} />
                  </group>
                </group>
                <group name="Drone_Outline" />
                <group name="Swings" position={[-6.283, 3, 6.252]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/comic_drone.glb')



